# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  projectName: 'Mendix.Widgets.Datagrid-web'
  widgetName: 'packages/pluggableWidgets/2G-datagrid-web'
  mpkName: 'com.2gplus.widget.web.Datagrid.mpk'
  widgetFolder: '2G-datagrid-web'
pool: Windows Build


steps:
  - task: BuildServer@0
    displayName: 'Get version'
    inputs:
      buildServerServiceName: 'BuildServer 2G'
      buildServerProject: $(projectName)
      buildType: 'milestone'
      command: start
  - task: UseNode@1
    inputs:
      version: '14.x'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
  - task: Npm@1
    displayName: 'Update build number'
    inputs:
      command: 'custom'
      workingDir: $(widgetName)
      customCommand: '--no-git-tag-version version $(Build.BuildNumber)'
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: 'custom'
      workingDir: $(widgetName)
      customCommand: 'run build'
  - task: BuildServer@0
    condition: failed()
    displayName: 'Abort version'
    inputs:
      buildServerServiceName: 'BuildServer 2G'
      buildServerProject: $(projectName)
      buildType: 'milestone'
      command: abort
  - task: BuildServer@0
    condition: succeeded()
    displayName: 'Commit version'
    inputs:
      buildServerServiceName: 'BuildServer 2G'
      buildServerProject: $(projectName)
      buildType: 'milestone'
      command: 'commit'
 
  - task: 2G-ProgetFeedUpload@0
    inputs:
      progetServiceName: '2G Proget'
      progetFeedName: 'upack/mendix-widgets'
      pathToPublish: '$(widgetName)/dist/$(Build.BuildNumber)/$(mpkName)'
      packageNameVersionRegex: '$(widgetFolder)\/dist\/(?<version>\d+.\d+.\d)\/(?<name>.*).mpk'


