# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool: Windows Build

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $version = node -p "require('./packages/pluggableWidgets/datagrid-web/package.json').version"
        Write-Host "##vso[task.setvariable variable=packageVersion;]$version"
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: 'custom'
      workingDir: 'packages/pluggableWidgets/datagrid-web'
      customCommand: 'run build'
  - task: 2G-ProgetFeedUpload@0
    inputs:
      progetServiceName: '2G Proget'
      progetFeedName: 'mendix-widgets'
      pathToPublish: 'packages/pluggableWidgets/datagrid-web/dist/$(packageVersion)/com.mendix.widget.web.Datagrid.mpk'
      packageNameVersionRegex: 'datagrid-web\/dist\/(?<version>\d+.\d+.\d)\/(?<name>.*).mpk'


